### ISSUE TITLE
blender coordinates of imported tifs

### ISSUE THREAD

**Issue by nikolas-claussen** [oanegros/MicroscopyNodes#54]
Hello, 

I am using blender to process surface meshes computed from 3d .tif stacks (e.g. a mesh of the surface of an organoid). I want to use MicroscopyNodes to import the original .tif into blender so I can overlay it with my mesh and see whether the mesh matches the raw data as intended.

My issue is as follows. From my .tif stack (for example 500 x 500 x100 pixels), I compute a mesh, saved as a .obj file. The vertex positions are in pixel coordinates, (i.e. x and y coordinates ranging from 0-500, z coordinate from 0-100 in the example). When I import both the mesh and .tif using MicroscopyNodes, the two objects do not overlap - the scales are completely different and it appears that the MicroscopyNode volume is also centered differently. Can you explain how exactly MicroscopyNodes maps image pixel coordinates to blender coordinates? Could you explain how to customize the coordinate choice (for example the centering)?
 
Best,

Nikolas

**Comment by oanegros** [comment]
Hi! this makes a lot of sense and in the long run i want to have a version of the loading interface where you can append obj or ilp files, as i've seen this is also relevant for EM data hosted on EMPIAR, for example. 

Until then, this is what Microscopy Nodes currently does:
- centers the object at (0.5, 0.5, 0)*shape of the object, meaning it centers the volume in x and y.
- scales it to 0.02 and stretches for anisotropy. This can also be assessed in the Geometry Nodes window for the axes object, as this requires µm to blender-meter calculations.

I hope this helps!

**Comment by nikolas-claussen** [comment]
Thanks - this is the info I needed!

Nikolas
