### ISSUE TITLE
Numpy 2.0 is breaking Molecular Nodes

### ISSUE THREAD

**Issue by BradyAJohnston** [oanegros/MicroscopyNodes#55]
For the extension package, the inclusion of Numpy 2.0 is breaking a bunch of stuff (including Molecular Nodes) as the higher version is taking precedence over the numpy that ships with Blender. 

Unless it is definitely required I would recommend adding it to the list of packages that are removed when building the .zips

**Comment by oanegros** [comment]
Yes, this was a mistake and unnecessary, will remove it asap :)
